### ISSUE TITLE
Upload compiled x86/x86-64 dynamic load library's

### ISSUE THREAD

**Issue by ghost** [carterjones/hello-world-dll#1]

**Comment by ghost** [comment]
I think the reason people would want to actually use this would be because they are too lazy to make a new visual studio project and compile a dll. It would not be because they are incapable of making a hello world. 

I think it would be wise if you uploaded a compiled x86-x86-64 dll for those people who need it.

**Comment by carterjones** [comment]
Thanks for opening this issue.

I added an AppVeyor config so it auto builds releases. There is a new release here: https://github.com/carterjones/hello-world-dll/releases/tag/v1.0.0

If this doesn't work for you, please feel free to re-open this issue.
